# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gogoodreads}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tim Medina"]
  s.date = %q{2011-03-24}
  s.description = %q{Allows you to progammatically pull book reviews from Goodreads using its API.}
  s.email = %q{iamteem@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "gogoodreads.gemspec",
    "lib/go_goodreads.rb",
    "lib/go_goodreads/attributes.rb",
    "lib/go_goodreads/author.rb",
    "lib/go_goodreads/book.rb",
    "lib/go_goodreads/comment.rb",
    "lib/go_goodreads/config.rb",
    "lib/go_goodreads/event.rb",
    "lib/go_goodreads/list.rb",
    "lib/go_goodreads/owned_book.rb",
    "lib/go_goodreads/quote.rb",
    "lib/go_goodreads/request.rb",
    "lib/go_goodreads/resource.rb",
    "lib/go_goodreads/review.rb",
    "lib/go_goodreads/shelf.rb",
    "lib/go_goodreads/user.rb",
    "lib/go_goodreads/user_status.rb",
    "lib/gogoodreads.rb",
    "spec/attribute_spec.rb",
    "spec/book_spec.rb",
    "spec/config_spec.rb",
    "spec/fixtures/vcr_cassettes/book_by_isbn.yml",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/iamteem/gogoodreads}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Goodreads API Ruby Interface}
  s.test_files = [
    "spec/attribute_spec.rb",
    "spec/book_spec.rb",
    "spec/config_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<vcr>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<vcr>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<vcr>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

